package myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Report implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "REPORT_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "REPORT_ID_SEQ", name = "REPORT_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.String user;

	private java.lang.String status;

	private java.util.Date date;

	@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	private java.util.List<myteam.ReportLine> lines;

	public Report() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.util.List<myteam.ReportLine> getLines() {
		return this.lines;
	}

	public void setLines(java.util.List<myteam.ReportLine> lines) {
		this.lines = lines;
	}

	public Report(java.lang.Long id, java.lang.String user,
			java.lang.String status, java.util.Date date,
			java.util.List<myteam.ReportLine> lines) {
		this.id = id;
		this.user = user;
		this.status = status;
		this.date = date;
		this.lines = lines;
	}

}