package myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ReportLine implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "REPORTLINE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "REPORTLINE_ID_SEQ", name = "REPORTLINE_ID_GENERATOR")
	private java.lang.Long id;

	private java.util.Date date;

	private java.lang.String description;

	private double amount;

	public ReportLine() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public ReportLine(java.lang.Long id, java.util.Date date,
			java.lang.String description, double amount) {
		this.id = id;
		this.date = date;
		this.description = description;
		this.amount = amount;
	}

}